package dev.orlyata.pinebobr;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import dev.orlyata.pinebobr.User;
import dev.orlyata.pinebobr.Value;

import dev.orlyata.pinebobr.UserDao;
import dev.orlyata.pinebobr.ValueDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig valueDaoConfig;

    private final UserDao userDao;
    private final ValueDao valueDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        valueDaoConfig = daoConfigMap.get(ValueDao.class).clone();
        valueDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        valueDao = new ValueDao(valueDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Value.class, valueDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        valueDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ValueDao getValueDao() {
        return valueDao;
    }

}
